### ISSUE TITLE
Error parsing string into single

### ISSUE THREAD

**Issue by toni15538** [Tamk1s/Thwimp#16] opened 2021-04-10 21:27 UTC
Well, the error is as the title says...

This problem occurs when I try to encode a thp file either through the GUI or the CLI.

What I've done to minimize the chance of this error:
-Copied the files in directories without spaces(directly on the root of the drive)
-I've moved all the needed files in the Thwimp directory (only FFmpeg, ffplay, and ffprobe on a subdirectory ff)

but after these actions, I still get this error.

Here's some basic info

OS: Win 10 with set Bulgarian UI language

Settings file:
**_[Thwimp.ini v1.2.0.0]
THPRoot = D:\wbfs\DATA\files\thp
FFMpegDir = C:\THWIMP\ff
FFplay_wdir = C:\THWIMP\ff
irfanview = C:\THWIMP\i_view32.exe
thpconv = C:\THWIMP\THPConv.exe
dataDir = 0
audio = 1
audio_bgm = 1
log_msgBox = 1
log_Full = 1_**

The file path selected for encoding is C:\single_top and all files are named like this (single_top_A1_1.mp4) and are the same resolutions/framerates as their original subvideos

There's nothing in the logfile even with the full log turned on, only this is saved:
**_MsgBox:
title: Error during Encoding!
msg: Error parsing string into Single
icon: DefaultButton1, OkOnly, Critical
Line number: 4762_**

Thanks in advance.

**Comment by Tamk1s** [comment] 2021-04-11 09:04
This seems to be a repeat of Issue #11 , which **should** be fixed already, but possibly not. I haven't been able to test the bugfix personally on a foreign culture machine.


**Quick technical details:**
First thing that I've noticed in the error report above is that your PC is of culture Bulgarian UI language on Windows 10, which is quite helpful for debugging the issue and the program flow.

As for the error itself, this is thrown by a function named "TryParseErr_Single" (at the bottom of the program code in main.vb) at line 4762. This function takes a string value as input (expected to be a decimal value encoded within a string), attempts to convert it to a single (decimal type) datatype, and either returns a single value if successful or an error. There are a few calls to this function within the program to attempt converting strings into single values, specifically for FPS handling.

As for your specific error, the problematic function call occurs at line 2923 in main.vb, at the beginning of the THP encoding process (in a subroutine aptly named "Encode"). At the beginning of that subroutine, metadata about the original THP file being replaced is fetched and converted from textboxes in the "THP Info" group box within the "THP" tab to their appropriate variable data types, for further processing during the encoding sequence. The textbox info itself is populated from your Thwimp datafile set used (specifically the fileset's FileData.txt).

At line 2923, the FPS data is fetched as a string from the "FPS" textbox, and then converted to a single. Looks like it is failing to parse the string as a single decimal type properly, hence the error. Within FileData.txt, the FPS string is expected to be formatted in invariant (EN-US) culture, in the format of **ww.dd** (**dot** character for separator, not "," comma), where w = whole part and d = decimal part. See Section 5 Customization of the manual for full details on the format and syntax of the Thwimp datafile set.


**So there are either 2 things happening here**
1. Bugfix for Issue #11 may not be fully working. I attempted fixing wrong parsing of FPS string data within TryParseErr_Single function by forcing EN-US/Invariant culture (**ww.dd dot char**) during parsing in the current build; however, the original poster of Issue #11 never replied back to confirm that it fixes the issue . Either that, or the bugfix has different behavior on Windows 10 with the older .NET 3.5 or so that this application has been compiled with. (I've only tested application on Windows 7 EN-US culture). If bugfix isn't working properly, try the workaround discussed in Issue #11 for now by temporarily changing Regional Settings as listed.

2. Incorrect syntax, formatting, or loading of the FileData.txt or other Thwimp fileset data. In the "Options" tab, point to the correct directory holding the Thwimp fileset data you wish to use (with files FileCDesc.txt, FileData.txt, FileDesc.txt, FileListing.txt, and FileSet.txt). Make sure the textboxes within "THP info" group box in the "THP" populate, and that the FPS data is displayed in EN-US format (**ww.dd**) .


If it's issue 1, I'll research a proper bugfix and implement it for a fixed build.

**Comment by Tamk1s** [comment] 2021-04-11 09:08
Please send me over a screenshot of both FileData.txt file used within the Thwimp fileset and of the "THP" tab contents after reproducing the bug during encoding, just to verify stuff is loading correctly on your end.

**Comment by toni15538** [comment] 2021-04-11 11:07
Here are the needed screenshots

Filedata.txt
![2021-04-11 14_01_03-FileData txt – Notepad](https://user-images.githubusercontent.com/24635225/114301693-9f362b80-9ace-11eb-8869-74c54e949904.png)

THP tab after error
![2021-04-11 13_59_38-Thwimp](https://user-images.githubusercontent.com/24635225/114301737-be34bd80-9ace-11eb-88ad-9d36b5a24de2.png)

After the detailed explanation, I will re-export the videos once again with Premiere Pro to see if that fixes this error. I'll let you know if it's fixed.

**Comment by toni15538** [comment] 2021-04-11 12:36
Finally made the thp video

Here's what I've done (hope this fixes issue  #15)

- With regional formatting set to Bulgarian I still have the directory parse error
- After temporarily setting the regional formatting to English(US)  Thwimp started encoding, but it stops in the ini hacking/searching. (as in issue 15)
- Reinstalled Irfanview with default settings and set the directory for the exe. Started Thwimp as admin. still the same error.
- Added [JPEG] with the two variables in the .ini file like this
![2021-04-11 15_15_22-i_view32 ini – Notepad](https://user-images.githubusercontent.com/24635225/114304032-baf2ff00-9ad9-11eb-897d-433d1dd8e2d3.png)

And Voila, Thwimp made a thp file without any error(even without admin rights).

Thanks again for the detailed description of the problems in both issues. It helped me.

**Comment by Tamk1s** [comment] 2021-04-11 16:36
I just noticed in your Thwimp screenshot that for some reason the FPS datafield within the "THP" tab has the FPS value set in foreign culture (59,94 with a **comma**), which would explain the Single parse fail error that you got when set in Bulgaria culture. Although the FileData.txt above has the FPS value strings formatted correctly in EN-US culture (ww.dd dot), the FPS textfield is displaying foreign culture.

I need to dig back in my code, but I may be storing the FPS value as a single datatype and then converting back to a string somewhere for the FPS textfield, and forgot to enforce the expected EN-US culture in the string conversion. This would totally explain the issue, and I'll need to put in a bugfix to fully fix Issue #11 .

Thanks for the bug report; I'll properly fix this within the week or so with a new minor build.

**Comment by Tamk1s** [comment] 2021-06-18 05:15
[Thwimp_v1201b.zip](https://github.com/Tamk1s/Thwimp/files/6674747/Thwimp_v1201b.zip)
@toni15538 Hey, sorry for the delay on fixing this issue! The development laptop died around April 14th and I had to earn enough money to directly replace the machine with the old hard drive inserted.


Attached is **Thwimp v1.2.0.1 beta** , which should fix this and other lingering invariant culture-related issues. Please try this build while using your normal regional formatting settings (Bulgarian); this should properly fix the "Error parsing string into single" error for the FPS formatting without workarounds. I'll test this on my end tomorrow and verify.

Please report back if this build fixes the Single parsing errors; if so, I'll close this issue and push a formal bugfixed release this week :).


**Summary of bugfixes:**
- Fixed issue with FPS textbox parsing
- Fixed issues with video start/end frame single strings for THP Viewer/Ripper cropper not using invariant culture for FFMPEG/FFPlay cmdline calls
- Fixed issues with FFMPEG calls using the FPS string value not using invariant culture while THP Encoding
- Fixed issues with the progress bar/application logger not using invariant culture for the progress bar percentage string values

**Comment by toni15538** [comment] 2021-06-20 20:05
Hello,

I'm sorry to hear, that your laptop broke, but now I'm happy, that you are back.

I've downloaded the latest version(1.2.0.1) and tried to make a new thp clip.
Now decoding/encoding works without changing the region setting.

Thanks again for the support.

**Comment by Tamk1s** [comment] 2021-06-20 21:58
Awesome! Glad to hear that it fixes the issues.

Will mark this issue as **Closed** and push out the official v1.2.0.1 release tonight.

**Closed as completed by Tamk1s** 2021-06-20 21:58 UTC
Labels: bug
